### ISSUE TITLE
First exon soft-clipped after second pass alignment 

### ISSUE THREAD

**Issue by skudashev** [bartongroup/2passtools#10]
Hello, 
Thank you for such a useful tool. 
I have noticed that an exon I am interested in is not soft-clipped after 1st pass alignment but is clipped out after I run minimap (with params: `-ax splice -k 14 -t 25 --secondary=no --junc-bed 2pass_juncs_filt.bed --junc-bonus 12`) with the junction bed generated with 2passtools. The 3' end splice junction is present in the 2pass_juncs_filt.bed. I guess the intron chain does not include TSSs, so I should expect the 5' end of the exon to be absent from the junction.bed. When running UCSC BLAT, the read aligns at 99% identity. What would you recommend in this case? 
Kind regards, 
Sofia

**Comment by mparker2** [comment]
Hi Sofia,
I'm not sure I totally understand the case you are describing. Is this a small terminal exon?
It would be helpful if you could provide some gene tracks showing the alignments for 1st and 2nd pass alignments, as well as the junctions in the filtered bed file.
Many thanks
Matt

**Comment by skudashev** [comment]
Hello Matt, 

It is a novel alternative first (5' UTR) exon. Issue is that it is only present in a few reads and they all have different start sites, but the 3' splice site is identical across all of them, and the start of the following exon is identical.  Here is an example of a read that had an almost perfect match when mapped to genome from position 1. 
1st pass CIGAR: `chr12	2054451	60	2S58M1D26M60688N5M1I77M1I209M1D30M4779N64M1I45M2I10M1D3M2D5M1I8M1D1M2D5M2D3M2D7M1D1M2D5M1D2M1I2M2I7M138660N1M6I11M2I1M1I4M8I1M2I12M7I2M198368N5I3M3I137M28397N10M1I30M1I119M6939N78M1D81M1D24M11049N14M3I90M8272N173M36958N56M1D34M6917N27M9444N161M986N14M1I5M2I18M2D143M2D42M13795N121M2D4M1I53M3D25M1024N64M1I57M1560N2D11M2D100M758N48M3I73M338N24M1I20M1D25M7308N133M2528N28M1D9M2D18M4I26M3D22M2I21M1433N60M4357N21M2I75M1D10M3120N39M2I8M1D40M510N83M1I17M3I8M824N53M320N31M1I102M1D13M1380N1M1I68M1D89M1D42M1828N7M2D31M1I72M1I47M1203N111M22283N84M14094N33M3132N94M1D34M2066N16M1D49M1246N29M2D31M36675N76M3D24M2I10M1D4M1D9M1D43M2I28M2D26M1D38M3I100M1I30M2D15M3D1M1D37M1D6M2D13M1I84M2D56M1I19M3I34M1I30M1I21M1D56M2D21M1D53M2D54M1D85M2D46M10S`
2nd pass CIGAR:
`chr12	2448975	60 515S22M1D22M2D25M1I4M1I60M3D2M8451N2M2D136M28397N10M1I30M1I119M6939N78M1D81M1D24M11049N14M3I90M8272N173M36958N56M1D34M6917N27M9444N161M986N14M1I5M2I18M2D143M2D42M13795N121M2D4M1I53M3D25M1024N64M1I57M1560N2D11M2D100M758N48M3I73M338N24M1I20M1D25M7308N133M2528N28M1D9M2D18M4I26M3D22M2I21M1433N60M4357N21M2I75M1D10M3120N39M2I8M1D40M510N83M1I17M3I8M824N53M320N31M1I102M1D13M1380N1M1I68M1D89M1D42M1828N7M2D31M1I72M1I47M1203N111M22283N84M14094N33M3132N94M1D34M2066N16M1D49M1246N29M2D36M5D7M1D4M4D1M3D36662N59M3D24M2I10M1D4M1D9M1D43M2I28M2D26M1D38M3I100M1I30M2D15M3D1M1D37M1D6M2D13M1I84M2D56M1I19M3I34M1I30M1I21M1D56M2D21M1D53M2D54M1D85M2D46M10S`
Corresponding junction for the missing exon from the 2pass filtered junctions file:
chr12	2004736	2115223	intron	0	+
chr12	2053611	2115223	intron	0	+
chr12	2054535	2115223	intron	0	+
Thank you very much for your help, 
Sofia

**Comment by mparker2** [comment]
Hi Sofia,

from the cigars you shared, it looks like its not just the first exon that is no longer aligned in that read, but the first four exons. In the first alignment, the third and fourth aligned introns are particularly large (139kb and 198kb) and so the penalty for aligning them will be quite big. In the second pass alignment, minimap2 has opted to softclip more of the 5' end and align a smaller region as an exon at chr12:2448975-2449116 with a much smaller 8.5kb intron at chr12:2449116-2457567.

My guess would be that the intron at chr12:2449116-2457567 is also in the 2passtools filtered junctions, and that the junction bonus for that intron is somehow sufficient to make the single exon/smaller intron alignment more favourable than the four exon/large intron alignment. But I can't be 100% sure of that without the original reads & the reference.

If I am right that the intron at chr12:2449116-2457567 is in the filtered junctions, and you don't think it should be, you could try filtering the junctions from the first pass alignment more stringently using 2passtools filter. You could also mess with the minimap2 parameters to try and recover the original alignment, e.g by reducing the gap extension penalty, reducing the junction bonus, etc. I'd be careful that you don't recover this alignment at the expense of alignment quality more generally, however.

Hope this helps
Matt

**Comment by skudashev** [comment]
Hello Matt, 

Thank you very much for your insight, it is very helpful and the soft-clip now makes sense. I will try tweaking the minimap junc and gap parameters, potentially increase the -G (max gap) as well. The  chr12:2449116-2457567 intron is in the filtered junction file, however I don't think I could filter it out as it has both very high supporting read count and JAD, and the intron is present in the gencode annotation. 
`chr12	2449115	2457566	GTAG	23	+	58	1	1	1	0.717	0.744	1`

Best wishes, 

Sofia
