### ISSUE TITLE
Process killed without description 

### ISSUE THREAD

**Issue by jadedavis5** [bartongroup/2passtools#11]
Hi,

I am running with: 
2passtools score -o nanopore_Maximus5_morexv2-aln_sorted.bed -f Morexv2_pseudomolecules.fasta nanopore_Maximus5_morexv2-aln-CS2_sorted.bam 

This runs for about 20 minutes but then ends without creating any output files with the log:

Parsing BAM file: nanopore_Maximus5_morexv2-aln-CS2_sorted.bam
Identified 189918 introns
Applying pretrained filter dt1
118650 introns pass filter dt1
Fetching junction sequences from Morexv2_pseudomolecules.fasta
Identified 157549 unique donors and 150769 unique acceptors
Scoring donor sequences with LR...
Scoring acceptor sequences with LR...
Killed

**Comment by mparker2** [comment]
sounds like you ran out of RAM or hit the memory limits of your OS
