### ISSUE TITLE
Mistake in pyranges cite :)

### ISSUE THREAD

**Issue by endrebak** [bartongroup/2passtools#2]
Hi --

thanks for citing pyranges - it is much appreciated. However, Hancock was the associate editor, not a coauthor :) The correct way to cite the NCLS/pyranges is

> Stovner, E. B. & Sætrom, P. PyRanges: efficient comparison of genomic intervals in Python. Bioinformatics, doi:10.1093/bioinformatics/btz615 (2019)

Anyways, good luck with publishing your paper.

**Comment by mparker2** [comment]
apologies this is probably an endnote error... I will make sure it is corrected if/when the paper is published
