### ISSUE TITLE
NameError: name 'jad_label' is not defined

### ISSUE THREAD

**Issue by wososa** [bartongroup/2passtools#4]
### Code:
`conda activate 2passtools`
`2passtools score -o 1pass.bed -f Homo_sapiens.GRCh38.dna.primary_assembly.fa 1pass.sorted.bam`

### Error:
Parsing BAM file: 1pass.sorted.bam
Identified 73631 introns
Applying pretrained filter dt1
`NameError: name 'jad_label' is not defined`

**Comment by mparker2** [comment]
Thanks. I just pushed a fix. Please try cloning again and retry
